package tiny;

/* Generated By:JJTree: Do not edit this line. ASTBEXP.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBEXP extends SimpleNode {
  public ASTBEXP(int id) {
    super(id);
  }

  public ASTBEXP(TinyLanguage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TinyLanguageVisitor visitor, Object data) throws SemanticException, ParseException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3bac4d51239ae6c71a831f40e6f1bdb6 (do not edit this line) */
