package tiny;

/* Generated By:JJTree: Do not edit this line. ASTCompoundCom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCompoundCom extends SimpleNode {
  public ASTCompoundCom(int id) {
    super(id);
  }

  public ASTCompoundCom(TinyLanguage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TinyLanguageVisitor visitor, Object data) throws SemanticException, ParseException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=79c6748afbc9ae729ac55e52c6d4e2b2 (do not edit this line) */
