package tiny;

/* Generated By:JJTree: Do not edit this line. ASTCom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCom extends SimpleNode {
  public ASTCom(int id) {
    super(id);
  }

  public ASTCom(TinyLanguage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TinyLanguageVisitor visitor, Object data) throws SemanticException, ParseException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5513ab53229675182187a69ce99eff07 (do not edit this line) */
