package tiny;

/* Generated By:JJTree: Do not edit this line. ASTProg.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProg extends SimpleNode {
  public ASTProg(int id) {
    super(id);
  }

  public ASTProg(TinyLanguage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TinyLanguageVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4df7f7accd837b1c70ccd7302fff49a4 (do not edit this line) */
