/* Generated By:JavaCC: Do not edit this line. TinyLanguageDefaultVisitor.java Version 7.0.10 */
package tiny;

public class TinyLanguageDefaultVisitor implements TinyLanguageVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProg node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSimpleCom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompoundCom node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAEXP node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBEXP node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=9559f8073935b8e9c8dd4c989c971f88 (do not edit this line) */
