/* Generated By:JJTree&JavaCC: Do not edit this line. TinyLanguageConstants.java */
package tiny;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinyLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int ARTHOPRND = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int EQUALS = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int SK = 22;
  /** RegularExpression Id. */
  int OPPAR = 23;
  /** RegularExpression Id. */
  int CLOSPAR = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "\"ff\"",
    "<VAR>",
    "\"tt\"",
    "\"+\"",
    "\"-\"",
    "<ARTHOPRND>",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"==\"",
    "\"!\"",
    "\"^\"",
    "\":=\"",
    "\";\"",
    "\"while\"",
    "\"do\"",
    "\"skip\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
  };

}
