/* Generated By:JavaCC: Do not edit this line. TinyLanguageTreeConstants.java Version 7.0.10 */
package tiny;

public interface TinyLanguageTreeConstants
{
  public int JJTPROG = 0;
  public int JJTCOM = 1;
  public int JJTSIMPLECOM = 2;
  public int JJTCOMPOUNDCOM = 3;
  public int JJTAEXP = 4;
  public int JJTBEXP = 5;


  public String[] jjtNodeName = {
    "Prog",
    "Com",
    "SimpleCom",
    "CompoundCom",
    "AEXP",
    "BEXP",
  };
}
/* JavaCC - OriginalChecksum=bceda29b7718e901599744070e5b9cef (do not edit this line) */
